/*
import Elm.Kernel.List exposing (toArray)
import Elm.Kernel.Scheduler exposing (binding, succeed, fail, rawSpawn)
import Elm.Kernel.Utils exposing (Tuple0, Tuple2)
import Bytes exposing (Bytes)
import Maybe exposing (Maybe)
*/
var _SchelmChildProcess_registry=new Map();
var _SchelmChildProcess_isUnix=process.platform==="linux";
function _SchelmChildProcess_code(x){return String(x&&(x.code||x.message)||x).slice(0,256);}
function _SchelmChildProcess_bytes(b){return new DataView(b.buffer,b.byteOffset,b.byteLength);}
function _SchelmChildProcess_maybeBytes(b){return b===null?$elm$core$Maybe$Nothing:$elm$core$Maybe$Just(_SchelmChildProcess_bytes(b));}
function _SchelmChildProcess_capture(stream,limit,overflow){var chunks=[],kept=0,over=false;if(!stream)return{finish:function(){return Buffer.alloc(0)}};stream.on("data",function(c){if(over)return;var room=limit-kept;if(c.length<=room){chunks.push(Buffer.from(c));kept+=c.length;}else{if(room>0){chunks.push(Buffer.from(c.subarray(0,room)));kept+=room;}over=true;overflow();}});return{finish:function(){return Buffer.concat(chunks,kept)}};}
function _SchelmChildProcess_signal(e,sig){try{process.kill(-e.pgid,sig);return "";}catch(x){return _SchelmChildProcess_code(x);}}
function _SchelmChildProcess_settleIo(e,reason){
  for(var side of ["Out","Err"]){var p=e["pending"+side];if(p){e["pending"+side]=null;p.finish(false,"CANCELLED:"+reason);}}
  if(e.writeWait){var w=e.writeWait;e.writeWait=null;e.writePending=false;w.finish(false,"CANCELLED:"+reason);}
  if(e.closeWait){var c=e.closeWait;e.closeWait=null;c.finish(false,"CANCELLED:"+reason);}
}
function _SchelmChildProcess_beginCleanup(e){
  if(e.cleaning)return;e.cleaning=true;_SchelmChildProcess_settleIo(e,e.reason||"transport");e.termError=_SchelmChildProcess_signal(e,"SIGTERM");
  e.termTimer=setTimeout(function(){e.killError=_SchelmChildProcess_signal(e,"SIGKILL");e.probes=[];function probe(){var result;try{process.kill(-e.pgid,0);result="present";}catch(x){result=x&&x.code==="ESRCH"?"gone":"failed:"+_SchelmChildProcess_code(x);}e.probes.push(result);if(result==="gone")return complete("gone");if(e.probes.length>=3)return complete(result);e.probeTimer=setTimeout(probe,25);}probe();},e.grace);
  function complete(detail){if(e.completed)return;e.completed=true;clearTimeout(e.termTimer);clearTimeout(e.probeTimer);clearTimeout(e.deadlineTimer);_SchelmChildProcess_registry.delete(e.id);var out=e.captureOut?e.captureOut.finish():null,err=e.captureErr?e.captureErr.finish():null;var evidence=_Utils_Tuple2(e.termError,_Utils_Tuple2(e.killError||"",_List_fromArray(e.probes||[])));_Scheduler_rawSpawn(A7(e.finish,e.code,e.signal,e.reason||"transport",detail,evidence,_SchelmChildProcess_maybeBytes(out),_SchelmChildProcess_maybeBytes(err)));}
}
var _SchelmChildProcess_start=F8(function(finish,id,program,argv,cwd,envFacts,stdinFacts,outputFacts){return _Scheduler_binding(function(callback){
  if(!_SchelmChildProcess_isUnix){callback(_Scheduler_succeed($elm$core$Result$Err("UNSUPPORTED_PLATFORM")));return;}
  var child,settled=false;function settle(v){if(!settled){settled=true;callback(_Scheduler_succeed(v));}}
  try{var ec=envFacts.a,pairs=_List_toArray(envFacts.b),env=ec===0?process.env:(ec===1?Object.assign(Object.create(null),process.env):Object.create(null));pairs.forEach(function(p){env[p.a]=p.b;});var sc=stdinFacts.a,sbytes=stdinFacts.b,of=outputFacts.a,sf=outputFacts.b.a,grace=outputFacts.b.b.a,deadline=outputFacts.b.b.b;function mode(x){return typeof x==="number"?x:x.a;}function limit(x){return typeof x==="number"?0:x.b;}
    child=require("node:child_process").spawn(program,_List_toArray(argv),{cwd:cwd.$==="Nothing"?undefined:cwd.a,env:env,detached:true,stdio:[sc===1?"inherit":(sc===0?"ignore":"pipe"),mode(of)===0?"inherit":(mode(of)===1?"ignore":"pipe"),mode(sf)===0?"inherit":(mode(sf)===1?"ignore":"pipe")]});
    var e={id:id,child:child,pgid:child.pid,grace:grace,finish:finish,cleaning:false,completed:false,code:-1,signal:"",stdout:child.stdout,stderr:child.stderr,stdin:child.stdin,endedOut:false,endedErr:false,captureOut:null,captureErr:null,reason:null,armed:false,closed:false,remainderOut:null,remainderErr:null,pendingOut:null,pendingErr:null,writePending:false,writeWait:null,closeWait:null,deadlineTimer:null};_SchelmChildProcess_registry.set(id,e);
    function overflowOut(){if(e.reason===null)e.reason="overflow-stdout";_SchelmChildProcess_beginCleanup(e);}function overflowErr(){if(e.reason===null)e.reason="overflow-stderr";_SchelmChildProcess_beginCleanup(e);}if(mode(of)===2&&typeof of!=="number")e.captureOut=_SchelmChildProcess_capture(e.stdout,limit(of),overflowOut);else if(e.stdout){e.stdout.pause();e.stdout.once("end",function(){e.endedOut=true;});}if(mode(sf)===2&&typeof sf!=="number")e.captureErr=_SchelmChildProcess_capture(e.stderr,limit(sf),overflowErr);else if(e.stderr){e.stderr.pause();e.stderr.once("end",function(){e.endedErr=true;});}
    child.once("spawn",function(){if(deadline>0)e.deadlineTimer=setTimeout(function(){if(e.reason===null)e.reason="deadline";_SchelmChildProcess_beginCleanup(e);},deadline);settle($elm$core$Result$Ok(child.pid));if(sc===2&&sbytes&&e.stdin){try{e.stdin.end(Buffer.from(sbytes.buffer,sbytes.byteOffset,sbytes.byteLength));}catch(x){if(e.reason===null)e.reason="input";_SchelmChildProcess_beginCleanup(e);}}});
    child.on("error",function(x){if(!settled){_SchelmChildProcess_registry.delete(id);settle($elm$core$Result$Err(_SchelmChildProcess_code(x)));}else{e.transportError=_SchelmChildProcess_code(x);if(e.reason===null)e.reason="transport";_SchelmChildProcess_beginCleanup(e);}});
    child.once("close",function(code,signal){e.code=code==null?-1:code;e.signal=signal||"";e.closed=true;if(e.reason===null)e.reason="leader";if(e.armed)_SchelmChildProcess_beginCleanup(e);});
  }catch(x){if(child)try{child.kill("SIGKILL");}catch(_){}settle($elm$core$Result$Err(_SchelmChildProcess_code(x)));}
  return function(){if(!settled&&child)try{process.kill(-child.pid,"SIGKILL");}catch(_){}};
});});
var _SchelmChildProcess_read=F2(function(id,stdout){return _Scheduler_binding(function(callback){var e=_SchelmChildProcess_registry.get(id),s=e&&(stdout?e.stdout:e.stderr);if(!e||!s){callback(_Scheduler_fail("UNAVAILABLE"));return;}var pk=stdout?"pendingOut":"pendingErr",rk=stdout?"remainderOut":"remainderErr";if(e[pk]){callback(_Scheduler_fail("ALREADY_PENDING"));return;}if(e[rk]){var rem=e[rk],part=rem.subarray(0,65536);e[rk]=rem.length>65536?rem.subarray(65536):null;callback(_Scheduler_succeed($elm$core$Maybe$Just(_SchelmChildProcess_bytes(part))));return;}if(stdout?e.endedOut:e.endedErr){callback(_Scheduler_succeed($elm$core$Maybe$Nothing));return;}var done=false;function clean(){e[pk]=null;s.removeListener("data",data);s.removeListener("end",end);s.removeListener("error",error);s.pause();}function finish(ok,value){if(done)return;done=true;clean();if(ok)callback(_Scheduler_succeed(value));else callback(_Scheduler_fail(value));}function data(b){if(b.length>65536)e[rk]=b.subarray(65536);finish(true,$elm$core$Maybe$Just(_SchelmChildProcess_bytes(b.subarray(0,65536))));}function end(){finish(true,$elm$core$Maybe$Nothing);}function error(x){finish(false,_SchelmChildProcess_code(x));}e[pk]={finish:finish};s.once("data",data);s.once("end",end);s.once("error",error);s.resume();return function(){finish(false,"CANCELLED:task");};});});
var _SchelmChildProcess_write=F2(function(id,bytes){return _Scheduler_binding(function(callback){var e=_SchelmChildProcess_registry.get(id);if(!e||!e.stdin){callback(_Scheduler_fail("UNAVAILABLE"));return;}if(e.writePending){callback(_Scheduler_fail("ALREADY_PENDING"));return;}e.writePending=true;var done=false;function clean(){e.writePending=false;e.writeWait=null;e.stdin.removeListener("drain",drain);e.stdin.removeListener("error",error);e.stdin.removeListener("close",closed);}function finish(ok,errorValue){if(done)return;done=true;clean();if(ok)callback(_Scheduler_succeed(_Utils_Tuple0));else callback(_Scheduler_fail(errorValue));}function drain(){finish(true,"");}function error(x){finish(false,"BROKEN_PIPE:"+_SchelmChildProcess_code(x));}function closed(){finish(false,"BROKEN_PIPE:close");}e.writeWait={finish:finish};e.stdin.once("error",error);e.stdin.once("close",closed);try{var b=Buffer.from(bytes.buffer,bytes.byteOffset,bytes.byteLength);if(e.stdin.write(b))finish(true,"");else e.stdin.once("drain",drain);}catch(x){error(x);}return function(){finish(false,"CANCELLED:task");};});});
var _SchelmChildProcess_close=function(id){return _Scheduler_binding(function(callback){var e=_SchelmChildProcess_registry.get(id);if(!e||!e.stdin){callback(_Scheduler_fail("UNAVAILABLE"));return;}var done=false;function clean(){e.closeWait=null;e.stdin.removeListener("finish",finished);e.stdin.removeListener("error",error);e.stdin.removeListener("close",closed);}function finish(ok,errorValue){if(done)return;done=true;clean();if(ok)callback(_Scheduler_succeed(_Utils_Tuple0));else callback(_Scheduler_fail(errorValue));}function finished(){finish(true,"");}function error(x){finish(false,"BROKEN_PIPE:"+_SchelmChildProcess_code(x));}function closed(){finish(false,"BROKEN_PIPE:close");}e.closeWait={finish:finish};e.stdin.once("finish",finished);e.stdin.once("error",error);e.stdin.once("close",closed);try{e.stdin.end();}catch(x){error(x);}return function(){finish(false,"CANCELLED:task");};});};
var _SchelmChildProcess_cancel=function(id){return _Scheduler_binding(function(callback){var e=_SchelmChildProcess_registry.get(id);if(e){if(e.reason===null)e.reason="cancel";_SchelmChildProcess_beginCleanup(e);}callback(_Scheduler_succeed(_Utils_Tuple0));});};
var _SchelmChildProcess_cancelMany=function(ids){return _Scheduler_binding(function(callback){_List_toArray(ids).forEach(function(id){var e=_SchelmChildProcess_registry.get(id);if(e){if(e.reason===null)e.reason="shutdown";_SchelmChildProcess_beginCleanup(e);}});callback(_Scheduler_succeed(_Utils_Tuple0));});};
var _SchelmChildProcess_arm=function(id){return _Scheduler_binding(function(callback){var e=_SchelmChildProcess_registry.get(id);callback(_Scheduler_succeed(_Utils_Tuple0));if(e)setTimeout(function(){e.armed=true;if(e.closed)_SchelmChildProcess_beginCleanup(e);},0);});};
