/*
import Elm.Kernel.List exposing (toArray)
import Elm.Kernel.Scheduler exposing (binding, succeed, fail, rawSpawn)
import Elm.Kernel.Utils exposing (Tuple0, Tuple2)
import Bytes exposing (Bytes)
import Maybe exposing (Maybe)
*/
var _SchelmChildProcess_registry=new Map();
var _SchelmChildProcess_parentNext=0;
var _SchelmChildProcess_parentReservations=new Map();
var _SchelmChildProcess_parentRequests=new Map();
var _SchelmChildProcess_parentListening=false;
function _SchelmChildProcess_parentListen(){if(_SchelmChildProcess_parentListening)return;process.addListener("message",_SchelmChildProcess_parentMessage);process.addListener("disconnect",_SchelmChildProcess_parentDisconnect);_SchelmChildProcess_parentListening=true;}
function _SchelmChildProcess_parentUnlisten(){if(!_SchelmChildProcess_parentListening||_SchelmChildProcess_parentRequests.size||_SchelmChildProcess_parentReservations.size)return;process.removeListener("message",_SchelmChildProcess_parentMessage);process.removeListener("disconnect",_SchelmChildProcess_parentDisconnect);_SchelmChildProcess_parentListening=false;}
function _SchelmChildProcess_parentDisconnect(){var pending=Array.from(_SchelmChildProcess_parentRequests.values());_SchelmChildProcess_parentRequests.clear();for(var request of pending){clearTimeout(request.timer);request.finish(false,"PARENT_TRANSPORT_LOST:disconnect");}for(var e of _SchelmChildProcess_registry.values()){if(e.parent&&e.parent.registration){if(e.reason===null)e.reason="transport";e.transportDetail="PARENT_TRANSPORT_LOST:disconnect";_SchelmChildProcess_beginCleanup(e);}}_SchelmChildProcess_parentReservations.clear();_SchelmChildProcess_parentUnlisten();}
function _SchelmChildProcess_parentMessage(message){if(!message||typeof message!=="object"||typeof message.request!=="number")return;var pending=_SchelmChildProcess_parentRequests.get(message.request);if(!pending||message.reservation!==pending.reservation||message.type!==pending.replyType)return;_SchelmChildProcess_parentRequests.delete(message.request);clearTimeout(pending.timer);pending.finish(message.ok!==false,message.detail||"");_SchelmChildProcess_parentUnlisten();}
function _SchelmChildProcess_parentRequest(type,replyType,reservation,payload,timeout,finish){if(typeof process.send!=="function"||!process.connected){finish(false,"PARENT_UNAVAILABLE");return;}var request=_SchelmChildProcess_parentNext++;var settled=false;function done(ok,detail){if(settled)return;settled=true;finish(ok,detail);}var pending={reservation:reservation,replyType:replyType,finish:done,timer:null};pending.timer=setTimeout(function(){_SchelmChildProcess_parentRequests.delete(request);done(false,"PARENT_TIMEOUT");_SchelmChildProcess_parentUnlisten();},timeout);_SchelmChildProcess_parentRequests.set(request,pending);_SchelmChildProcess_parentListen();try{process.send(Object.assign({type:type,request:request,reservation:reservation},payload||{}),function(error){if(error){_SchelmChildProcess_parentRequests.delete(request);clearTimeout(pending.timer);done(false,"PARENT_TRANSPORT_LOST:"+_SchelmChildProcess_code(error));_SchelmChildProcess_parentUnlisten();}});}catch(error){_SchelmChildProcess_parentRequests.delete(request);clearTimeout(pending.timer);done(false,"PARENT_TRANSPORT_LOST:"+_SchelmChildProcess_code(error));_SchelmChildProcess_parentUnlisten();}}
var _SchelmChildProcess_parentPrepare=function(timeout){return _Scheduler_binding(function(callback){if(_SchelmChildProcess_parentNext>=9007199254740990){callback(_Scheduler_fail("RESERVATION_EXHAUSTED"));return;}var reservation=_SchelmChildProcess_parentNext++;_SchelmChildProcess_parentRequest("schelm-child.prepare","schelm-child.prepared",reservation,null,timeout,function(ok,detail){if(ok){_SchelmChildProcess_parentReservations.set(reservation,{timeout:timeout,claimed:false,used:false});callback(_Scheduler_succeed(reservation));}else callback(_Scheduler_fail(detail));});});};
var _SchelmChildProcess_parentClaim=function(reservation){return _Scheduler_binding(function(callback){var slot=_SchelmChildProcess_parentReservations.get(reservation);if(!slot||slot.claimed){callback(_Scheduler_succeed(false));return;}slot.claimed=true;callback(_Scheduler_succeed(true));});};
var _SchelmChildProcess_parentBind=F3(function(id,reservation,timeout){return _Scheduler_binding(function(callback){var e=_SchelmChildProcess_registry.get(id),slot=_SchelmChildProcess_parentReservations.get(reservation);if(!e||!slot||!slot.claimed||slot.used){callback(_Scheduler_fail("INVALID_RESERVATION"));return;}slot.used=true;_SchelmChildProcess_parentRequest("schelm-child.bind","schelm-child.bound",reservation,{pid:e.child.pid,pgid:e.pgid},timeout,function(ok,detail){if(ok){e.parent={reservation:reservation,timeout:timeout,registration:true,beforeKill:false};callback(_Scheduler_succeed(_Utils_Tuple2(e.child.pid,e.pgid)));}else{_SchelmChildProcess_parentReservations.delete(reservation);callback(_Scheduler_fail(detail));}});});});
var _SchelmChildProcess_isUnix=process.platform==="linux";
function _SchelmChildProcess_code(x){return String(x&&(x.code||x.message)||x).slice(0,256);}
function _SchelmChildProcess_bytes(b){return new DataView(b.buffer,b.byteOffset,b.byteLength);}
function _SchelmChildProcess_maybeBytes(b){return b===null?$elm$core$Maybe$Nothing:$elm$core$Maybe$Just(_SchelmChildProcess_bytes(b));}
function _SchelmChildProcess_capture(stream,limit,overflow){var chunks=[],kept=0,over=false;if(!stream)return{finish:function(){return Buffer.alloc(0)}};stream.on("data",function(c){if(over)return;var room=limit-kept;if(c.length<=room){chunks.push(Buffer.from(c));kept+=c.length;}else{if(room>0){chunks.push(Buffer.from(c.subarray(0,room)));kept+=room;}over=true;overflow();}});return{finish:function(){return Buffer.concat(chunks,kept)}};}
function _SchelmChildProcess_signal(e,sig){try{process.kill(-e.pgid,sig);return "";}catch(x){return _SchelmChildProcess_code(x);}}
function _SchelmChildProcess_maybeClosedCleanup(e){if(e.armed&&e.closed&&(!e.demandOut||e.endedOut)&&(!e.demandErr||e.endedErr))_SchelmChildProcess_beginCleanup(e);}
function _SchelmChildProcess_settleIo(e,reason){
  for(var side of ["Out","Err"]){var p=e["pending"+side];if(p){e["pending"+side]=null;p.finish(false,"CANCELLED:"+reason);}}
  if(e.writeWait){var w=e.writeWait;e.writeWait=null;e.writePending=false;w.finish(false,"CANCELLED:"+reason);}
  if(e.closeWait){var c=e.closeWait;e.closeWait=null;c.finish(false,"CANCELLED:"+reason);}
}
function _SchelmChildProcess_beginCleanup(e){
  if(e.cleanup)return;e.cleanup={phase:"term",registration:!!(e.parent&&e.parent.registration),beforeKill:"not-requested"};_SchelmChildProcess_settleIo(e,e.reason||"transport");e.termError=_SchelmChildProcess_signal(e,"SIGTERM");
  e.termTimer=setTimeout(function(){function killNow(){e.cleanup.phase="kill";e.killError=_SchelmChildProcess_signal(e,"SIGKILL");e.probes=[];function probe(){var result;try{process.kill(-e.pgid,0);result="present";}catch(x){result=x&&x.code==="ESRCH"?"gone":"failed:"+_SchelmChildProcess_code(x);}e.probes.push(result);if(result==="gone")return complete("gone");if(e.probes.length>=3)return complete(result);e.probeTimer=setTimeout(probe,25);}probe();}if(e.cleanup.registration){e.cleanup.phase="before-kill";_SchelmChildProcess_parentRequest("schelm-child.before-kill","schelm-child.reaped",e.parent.reservation,{pid:e.child.pid,pgid:e.pgid},e.parent.timeout,function(ok,detail){e.cleanup.beforeKill=ok?"ack":(detail==="PARENT_TIMEOUT"?"timeout":"failed:"+detail);killNow();});}else killNow();},e.grace);
  function complete(detail){if(e.cleanup.phase==="unregister"||e.cleanup.phase==="absent")return;clearTimeout(e.termTimer);clearTimeout(e.probeTimer);clearTimeout(e.deadlineTimer);function absent(){e.cleanup.phase="absent";_SchelmChildProcess_registry.delete(e.id);var out=e.captureOut?e.captureOut.finish():null,err=e.captureErr?e.captureErr.finish():null;var evidence=_Utils_Tuple2(e.termError,_Utils_Tuple2(e.killError||"",_Utils_Tuple2(e.cleanup.beforeKill,_List_fromArray(e.probes||[]))));setTimeout(function(){_Scheduler_rawSpawn(A8(e.finish,e.code,e.signal,e.reason||"transport",e.transportDetail||"",detail,evidence,_SchelmChildProcess_maybeBytes(out),_SchelmChildProcess_maybeBytes(err)));},0);}if(e.cleanup.registration){e.cleanup.phase="unregister";_SchelmChildProcess_parentRequest("schelm-child.unregister","schelm-child.unregistered",e.parent.reservation,{pid:e.child.pid,pgid:e.pgid},e.parent.timeout,function(){e.cleanup.registration=false;e.parent.registration=false;_SchelmChildProcess_parentReservations.delete(e.parent.reservation);_SchelmChildProcess_parentUnlisten();absent();});}else absent();}
}
var _SchelmChildProcess_start=F8(function(finish,id,program,argv,cwd,envFacts,stdinFacts,outputFacts){return _Scheduler_binding(function(callback){
  if(!_SchelmChildProcess_isUnix){callback(_Scheduler_succeed($elm$core$Result$Err("UNSUPPORTED_PLATFORM")));return;}
  var child,settled=false;function settle(v){if(!settled){settled=true;callback(_Scheduler_succeed(v));}}
  try{var ec=envFacts.a,pairs=_List_toArray(envFacts.b),env=ec===0?process.env:(ec===1?Object.assign(Object.create(null),process.env):Object.create(null));pairs.forEach(function(p){env[p.a]=p.b;});var sc=stdinFacts.a,sbytes=stdinFacts.b,of=outputFacts.a,sf=outputFacts.b.a,grace=outputFacts.b.b.a,deadline=outputFacts.b.b.b;function mode(x){return typeof x==="number"?x:x.a;}function limit(x){return typeof x==="number"?0:x.b;}
    child=require("node:child_process").spawn(program,_List_toArray(argv),{cwd:cwd.$==="Nothing"?undefined:cwd.a,env:env,detached:true,stdio:[sc===1?"inherit":(sc===0?"ignore":"pipe"),mode(of)===0?"inherit":(mode(of)===1?"ignore":"pipe"),mode(sf)===0?"inherit":(mode(sf)===1?"ignore":"pipe")]});
    var e={id:id,child:child,pgid:child.pid,grace:grace,finish:finish,cleanup:null,code:-1,signal:"",stdout:child.stdout,stderr:child.stderr,stdin:child.stdin,endedOut:false,endedErr:false,captureOut:null,captureErr:null,reason:null,armed:false,closed:false,remainderOut:null,remainderErr:null,pendingOut:null,pendingErr:null,writePending:false,writeWait:null,closeWait:null,deadlineTimer:null,stdinClosed:sc===0||sc===1,transportDetail:"",demandOut:mode(of)===2&&typeof of==="number",demandErr:mode(sf)===2&&typeof sf==="number"};_SchelmChildProcess_registry.set(id,e);
    function overflowOut(){if(e.reason===null)e.reason="overflow-stdout";_SchelmChildProcess_beginCleanup(e);}function overflowErr(){if(e.reason===null)e.reason="overflow-stderr";_SchelmChildProcess_beginCleanup(e);}if(mode(of)===2&&typeof of!=="number")e.captureOut=_SchelmChildProcess_capture(e.stdout,limit(of),overflowOut);else if(e.stdout){e.stdout.pause();e.stdout.once("end",function(){e.endedOut=true;_SchelmChildProcess_maybeClosedCleanup(e);});}if(mode(sf)===2&&typeof sf!=="number")e.captureErr=_SchelmChildProcess_capture(e.stderr,limit(sf),overflowErr);else if(e.stderr){e.stderr.pause();e.stderr.once("end",function(){e.endedErr=true;_SchelmChildProcess_maybeClosedCleanup(e);});}
    child.once("spawn",function(){if(deadline>0)e.deadlineTimer=setTimeout(function(){if(e.reason===null)e.reason="deadline";_SchelmChildProcess_beginCleanup(e);},deadline);settle($elm$core$Result$Ok(child.pid));if(sc===2&&sbytes&&e.stdin){try{e.stdin.end(Buffer.from(sbytes.buffer,sbytes.byteOffset,sbytes.byteLength));}catch(x){e.transportDetail="BROKEN_PIPE:"+_SchelmChildProcess_code(x);if(e.reason===null)e.reason="input";_SchelmChildProcess_beginCleanup(e);}}});
    child.on("error",function(x){if(!settled){_SchelmChildProcess_registry.delete(id);settle($elm$core$Result$Err(_SchelmChildProcess_code(x)));}else{e.transportDetail=_SchelmChildProcess_code(x);if(e.reason===null)e.reason="transport";_SchelmChildProcess_beginCleanup(e);}});
    child.once("close",function(code,signal){e.code=code==null?-1:code;e.signal=signal||"";e.closed=true;if(e.reason===null)e.reason="leader";_SchelmChildProcess_maybeClosedCleanup(e);});
  }catch(x){if(child)try{child.kill("SIGKILL");}catch(_){}settle($elm$core$Result$Err(_SchelmChildProcess_code(x)));}
  return function(){if(!settled&&child)try{process.kill(-child.pid,"SIGKILL");}catch(_){}};
});});
var _SchelmChildProcess_read=F2(function(id,stdout){return _Scheduler_binding(function(callback){var e=_SchelmChildProcess_registry.get(id),s=e&&(stdout?e.stdout:e.stderr);if(e)e.armed=true;if(!e||!s){callback(_Scheduler_fail("UNAVAILABLE"));return;}var pk=stdout?"pendingOut":"pendingErr",rk=stdout?"remainderOut":"remainderErr";if(e[pk]){callback(_Scheduler_fail("ALREADY_PENDING"));return;}if(e[rk]){var rem=e[rk],part=rem.subarray(0,65536);e[rk]=rem.length>65536?rem.subarray(65536):null;callback(_Scheduler_succeed($elm$core$Maybe$Just(_SchelmChildProcess_bytes(part))));return;}if(stdout?e.endedOut:e.endedErr){callback(_Scheduler_succeed($elm$core$Maybe$Nothing));return;}var done=false;function clean(){e[pk]=null;s.removeListener("data",data);s.removeListener("end",end);s.removeListener("error",error);s.pause();}function finish(ok,value){if(done)return;done=true;clean();if(ok)callback(_Scheduler_succeed(value));else callback(_Scheduler_fail(value));}function data(b){if(b.length>65536)e[rk]=b.subarray(65536);finish(true,$elm$core$Maybe$Just(_SchelmChildProcess_bytes(b.subarray(0,65536))));}function end(){finish(true,$elm$core$Maybe$Nothing);}function error(x){finish(false,_SchelmChildProcess_code(x));}e[pk]={finish:finish};s.once("data",data);s.once("end",end);s.once("error",error);s.resume();return function(){finish(false,"CANCELLED:task");};});});
var _SchelmChildProcess_write=F2(function(id,bytes){return _Scheduler_binding(function(callback){var e=_SchelmChildProcess_registry.get(id);if(!e||!e.stdin){callback(_Scheduler_fail("UNAVAILABLE"));return;}if(e.stdinClosed){callback(_Scheduler_fail("CLOSED"));return;}if(e.writePending||e.closeWait){callback(_Scheduler_fail("ALREADY_PENDING"));return;}e.writePending=true;var done=false;function clean(){e.writePending=false;e.writeWait=null;e.stdin.removeListener("drain",drain);e.stdin.removeListener("error",error);e.stdin.removeListener("close",closed);}function finish(ok,errorValue){if(done)return;done=true;clean();if(ok)callback(_Scheduler_succeed(_Utils_Tuple0));else callback(_Scheduler_fail(errorValue));}function drain(){finish(true,"");}function error(x){finish(false,"BROKEN_PIPE:"+_SchelmChildProcess_code(x));}function closed(){finish(false,"BROKEN_PIPE:close");}e.writeWait={finish:finish};e.stdin.once("error",error);e.stdin.once("close",closed);try{var b=Buffer.from(bytes.buffer,bytes.byteOffset,bytes.byteLength);if(e.stdin.write(b))finish(true,"");else e.stdin.once("drain",drain);}catch(x){error(x);}return function(){finish(false,"CANCELLED:task");};});});
var _SchelmChildProcess_close=function(id){return _Scheduler_binding(function(callback){var e=_SchelmChildProcess_registry.get(id);if(!e||!e.stdin){callback(_Scheduler_fail("UNAVAILABLE"));return;}if(e.stdinClosed){callback(_Scheduler_fail("CLOSED"));return;}if(e.writePending||e.writeWait||e.closeWait){callback(_Scheduler_fail("ALREADY_PENDING"));return;}var done=false;function clean(){e.closeWait=null;e.stdin.removeListener("finish",finished);e.stdin.removeListener("error",error);e.stdin.removeListener("close",closed);}function finish(ok,errorValue){if(done)return;done=true;clean();if(ok)callback(_Scheduler_succeed(_Utils_Tuple0));else callback(_Scheduler_fail(errorValue));}function finished(){e.stdinClosed=true;finish(true,"");}function error(x){finish(false,"BROKEN_PIPE:"+_SchelmChildProcess_code(x));}function closed(){finish(false,"BROKEN_PIPE:close");}e.closeWait={finish:finish};e.stdin.once("finish",finished);e.stdin.once("error",error);e.stdin.once("close",closed);try{e.stdin.end();}catch(x){error(x);}return function(){finish(false,"CANCELLED:task");};});};
var _SchelmChildProcess_cancel=function(id){return _Scheduler_binding(function(callback){var e=_SchelmChildProcess_registry.get(id);if(e){if(e.reason===null)e.reason="cancel";_SchelmChildProcess_beginCleanup(e);}callback(_Scheduler_succeed(_Utils_Tuple0));});};
var _SchelmChildProcess_cancelMany=function(ids){return _Scheduler_binding(function(callback){_List_toArray(ids).forEach(function(id){var e=_SchelmChildProcess_registry.get(id);if(e){if(e.reason===null)e.reason="shutdown";_SchelmChildProcess_beginCleanup(e);}});callback(_Scheduler_succeed(_Utils_Tuple0));});};
var _SchelmChildProcess_arm=function(id){return _Scheduler_binding(function(callback){var e=_SchelmChildProcess_registry.get(id);callback(_Scheduler_succeed(_Utils_Tuple0));if(e)setTimeout(function(){e.armed=true;_SchelmChildProcess_maybeClosedCleanup(e);},0);});};
